### ISSUE TITLE
数据库报错

### ISSUE THREAD

**Issue by FuShaoLei** [imlinhanchao/cashflow#2]
![image](https://github.com/user-attachments/assets/9de664ce-cb65-4e39-b310-a2e56af08170)

应该是找不到对应的表名，应该去哪里修改？ 用的是mysql8.0

**Comment by imlinhanchao** [comment]
不是找不到表名，是连接不上数据库，确认一下数据配置是否正确。到dist/config/config.json 看看

**Comment by FuShaoLei** [comment]
@imlinhanchao 谢了，可以了。顺便说一下，config.json 是在根目录下，不再dist/config目录

**Comment by imlinhanchao** [comment]
噢噢，我以为你是debug启动
